# Generated by Django 5.2.1 on 2025-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_domicilio_persona_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='no_calle',
            field=models.IntegerField(),
        ),
    ]
